version: "3.4"
services:
  nodejs:
    container_name: kartaca-server
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
      - redis
  nextjs:
    container_name: kartaca-client
    build: ./client
    ports:
      - "3000:3000"
  mongodb:
    container_name: kartaca-db
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - data:/data/db
  redis:
    container_name: kartaca-redis
    image: redis
    ports:
      - "6379:6379"
volumes:
  data:
